export {default as App} from './App';
export {default as Home} from './Home';
export {default as Header} from './Header';
export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as Post} from './Post';
export {default as PostsPage} from './Posts';
export {default as User} from './User';
export {default as DeletePost} from './DeletePost';